# Generated by Django 2.2.6 on 2019-10-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0006_auto_20191010_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
