# Generated by Django 2.2.6 on 2019-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='profile_images'),
        ),
    ]
